// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNj8eJJWEb-VabsaQvkVa6C972GRXjAYM',
    appId: '1:5584921264:web:df3719aa399276e0f8d175',
    messagingSenderId: '5584921264',
    projectId: 'flutter-orb',
    authDomain: 'flutter-orb.firebaseapp.com',
    storageBucket: 'flutter-orb.firebasestorage.app',
    measurementId: 'G-T9ZME0KD7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCto4DV4PI3gD0DfIlKacZ_28qC9AQs7mk',
    appId: '1:5584921264:android:d0cc147daf5f9261f8d175',
    messagingSenderId: '5584921264',
    projectId: 'flutter-orb',
    storageBucket: 'flutter-orb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzpcsBf_fvpv9EIJGxhE65ELbnnnCpXEA',
    appId: '1:5584921264:ios:6b84cc767f132eecf8d175',
    messagingSenderId: '5584921264',
    projectId: 'flutter-orb',
    storageBucket: 'flutter-orb.firebasestorage.app',
    iosBundleId: 'com.halooid.orbView',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzpcsBf_fvpv9EIJGxhE65ELbnnnCpXEA',
    appId: '1:5584921264:ios:6b84cc767f132eecf8d175',
    messagingSenderId: '5584921264',
    projectId: 'flutter-orb',
    storageBucket: 'flutter-orb.firebasestorage.app',
    iosBundleId: 'com.halooid.orbView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNj8eJJWEb-VabsaQvkVa6C972GRXjAYM',
    appId: '1:5584921264:web:94337780d0792959f8d175',
    messagingSenderId: '5584921264',
    projectId: 'flutter-orb',
    authDomain: 'flutter-orb.firebaseapp.com',
    storageBucket: 'flutter-orb.firebasestorage.app',
    measurementId: 'G-SPMJG23SH6',
  );
}
