name: Publish to pub.dev & Deploy Web Demo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for authentication using OIDC on pub.dev

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

  deploy-web:
    name: Deploy Web to Firebase Hosting
    needs: [publish]
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy_web.yml
    secrets: inherit
    with:
      channel: 'live'
